/**
 * Seed Kampung table from the scraped NADI Selangor dataset.
 *
 * Idempotent — uses upsert so re-running is safe. Maps each NADI centre
 * (id like "selangor-felda-gedangsa") into a Kampung row with:
 *   - id          → cuid (generated by Prisma)
 *   - name        → centre name (UPPERCASE)
 *   - state       → "Selangor"
 *   - districtHint→ from scraper
 *   - nadiCentreId→ scraper id (unique key for upsert)
 *
 * Run:
 *   pnpm --filter db tsx prisma/seed-kampung.ts
 */

import "dotenv/config";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { prisma } from "../src/index.js";

type NadiCentre = {
  id: string;
  name: string;
  state: string;
  district_hint: string | null;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_PATH = join(
  __dirname,
  "..",
  "..",
  "backend",
  "src",
  "data",
  "nadi-centres-selangor.json",
);

async function main() {
  console.log(`[seed-kampung] reading ${DATA_PATH}`);
  const raw = readFileSync(DATA_PATH, "utf-8");
  const centres = JSON.parse(raw) as NadiCentre[];
  console.log(`[seed-kampung] found ${centres.length} centres`);

  let created = 0;
  let updated = 0;

  for (const centre of centres) {
    const result = await prisma.kampung.upsert({
      where: { nadiCentreId: centre.id },
      create: {
        name: centre.name,
        state: centre.state,
        districtHint: centre.district_hint,
        nadiCentreId: centre.id,
      },
      update: {
        name: centre.name,
        districtHint: centre.district_hint,
      },
    });
    if (result.updatedAt.getTime() === result.createdAt.getTime()) {
      created += 1;
    } else {
      updated += 1;
    }
  }

  console.log(`[seed-kampung] created=${created}, updated=${updated}`);

  // Sanity check — Felda Gedangsa must exist
  const felda = await prisma.kampung.findUnique({
    where: { nadiCentreId: "selangor-felda-gedangsa" },
  });
  console.log(
    felda
      ? `[seed-kampung] ✓ FELDA GEDANGSA seeded (id=${felda.id}, district=${felda.districtHint})`
      : `[seed-kampung] ✗ FELDA GEDANGSA missing!`,
  );

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("[seed-kampung] failed:", err);
  process.exit(1);
});
