/**
 * Seed Kampung table from the scraped NADI Selangor dataset.
 *
 * Idempotent — uses upsert so re-running is safe. Maps each NADI centre
 * (id like "selangor-felda-gedangsa") into a Kampung row with:
 *   - id          → cuid (generated by Prisma)
 *   - name        → centre name (UPPERCASE)
 *   - state       → "Selangor"
 *   - districtHint→ from scraper
 *   - nadiCentreId→ scraper id (unique key for upsert)
 *
 * Two ways to invoke:
 *   1. Standalone CLI:   pnpm --filter db exec tsx prisma/seed-kampung.ts
 *   2. Via seed-runner:  imported as { name, run } and gated by _seed_history.
 */

import "dotenv/config";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { PrismaClient } from "@prisma/client";
import { prisma } from "../src/index.js";

type NadiCentre = {
  id: string;
  name: string;
  state: string;
  district_hint: string | null;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_PATH = join(
  __dirname,
  "..",
  "..",
  "backend",
  "src",
  "data",
  "nadi-centres-selangor.json",
);

export const name = "2026-04-25_kampungs_from_nadi";

export async function run(client: PrismaClient = prisma) {
  console.log(`[seed-kampung] reading ${DATA_PATH}`);
  const raw = readFileSync(DATA_PATH, "utf-8");
  const centres = JSON.parse(raw) as NadiCentre[];
  console.log(`[seed-kampung] found ${centres.length} centres`);

  let created = 0;
  let updated = 0;

  for (const centre of centres) {
    const result = await client.kampung.upsert({
      where: { nadiCentreId: centre.id },
      create: {
        name: centre.name,
        state: centre.state,
        districtHint: centre.district_hint,
        nadiCentreId: centre.id,
      },
      update: {
        name: centre.name,
        districtHint: centre.district_hint,
      },
    });
    if (result.updatedAt.getTime() === result.createdAt.getTime()) {
      created += 1;
    } else {
      updated += 1;
    }
  }

  console.log(`[seed-kampung] created=${created}, updated=${updated}`);

  const felda = await client.kampung.findUnique({
    where: { nadiCentreId: "selangor-felda-gedangsa" },
  });
  console.log(
    felda
      ? `[seed-kampung] ✓ FELDA GEDANGSA seeded (id=${felda.id}, district=${felda.districtHint})`
      : `[seed-kampung] ✗ FELDA GEDANGSA missing!`,
  );
}

// CLI entrypoint — only runs when invoked directly via tsx prisma/seed-kampung.ts
const isDirectInvocation =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("seed-kampung.ts");

if (isDirectInvocation) {
  run()
    .catch((err) => {
      console.error("[seed-kampung] failed:", err);
      process.exit(1);
    })
    .finally(() => prisma.$disconnect());
}
